/**
 * scripts/redeploy-local.mjs
 *
 * Пересборка и деплой:
 *   1. PropertyOracle
 *   2. RealEstateMarket
 *
 * Обновляет frontend/src/contractConfig.js и oracle-backend/.env автоматически.
 *
 * Использование:
 *   node scripts/redeploy-local.mjs
 *
 * Требования:
 *   - Запущен Hardhat node: npx hardhat node
 *   - Затем в другом терминале: node scripts/redeploy-local.mjs
 */

import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const FRONTEND_CONFIG = "frontend/src/contractConfig.js";
const ORACLE_ENV = "oracle-backend/.env";

// ── Hardhat local accounts ──────────────────────────────────────────────────
// #0 deployer/seller
const SELLER  = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266";
// #1 buyer
const BUYER   = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8";
// #2 oracle fulfiller (private key from hardhat)
const FULFILLER_PK = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"; // account #0 (deployer, always has ETH)

console.log("🔄 Очищаю артефакты...");
execSync("rm -rf ignition/deployments artifacts cache frontend/node_modules/.vite", {
  stdio: "inherit",
});

console.log("🔨 Компилирую контракты...");
execSync("npx hardhat compile", { stdio: "inherit" });

console.log("🚀 Деплою оракул и маркетплейс...");
const output = execSync(
  "npx hardhat ignition deploy ./ignition/modules/RealEstateMarket.ts --network localhost",
  { encoding: "utf8" }
);
console.log(output);

// ── Парсим адреса из вывода Ignition ────────────────────────────────────────
const oracleMatch = output.match(/RealEstateMarketModule#PropertyOracle\s*-\s*(0x[a-fA-F0-9]{40})/);
const marketMatch = output.match(/RealEstateMarketModule#RealEstateMarket\s*-\s*(0x[a-fA-F0-9]{40})/);

if (!oracleMatch || !marketMatch) {
  console.error("❌ Не удалось найти адреса контрактов:");
  console.error(output);
  process.exit(1);
}

const ORACLE_ADDRESS = oracleMatch[1];
const MARKET_ADDRESS = marketMatch[1];

console.log(`✅ PropertyOracle:   ${ORACLE_ADDRESS}`);
console.log(`✅ RealEstateMarket: ${MARKET_ADDRESS}`);

// ── Обновляем frontend/src/contractConfig.js ─────────────────────────────────
const newConfig = generateFrontendConfig(MARKET_ADDRESS, ORACLE_ADDRESS, SELLER, BUYER);
fs.writeFileSync(FRONTEND_CONFIG, newConfig);
console.log(`✅ Обновлён: ${FRONTEND_CONFIG}`);

// ── Создаём / обновляем oracle-backend/.env ──────────────────────────────────
const envContent = `RPC_URL=http://127.0.0.1:8545
ORACLE_ADDRESS=${ORACLE_ADDRESS}
MARKET_ADDRESS=${MARKET_ADDRESS}
FULFILLER_PRIVATE_KEY=${FULFILLER_PK}
PORT=3001
`;

fs.mkdirSync("oracle-backend", { recursive: true });
fs.writeFileSync(ORACLE_ENV, envContent);
console.log(`✅ Создан: ${ORACLE_ENV}`);

console.log(`
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Готово! Следующие шаги:

  1. Запусти оракул-бэкенд (в отдельном терминале):
     cd oracle-backend && node server.mjs

  2. Запусти фронтенд:
     cd frontend && npm run dev -- --force

  3. В MetaMask подключи сеть Hardhat (chainId 31337)
     и импортируй аккаунты:
       Продавец (#0): 0xf39F...
       Покупатель (#1): 0x7099...
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`);

// ── Генерация contractConfig.js ──────────────────────────────────────────────
function generateFrontendConfig(marketAddr, oracleAddr, seller, buyer) {
  return `// Auto-generated by scripts/redeploy-local.mjs
// ${new Date().toISOString()}

export const MARKET_ADDRESS = "${marketAddr}";
export const ORACLE_ADDRESS = "${oracleAddr}";

export const SELLER = "${seller}";
export const BUYER  = "${buyer}";

// ─── PropertyOracle ABI ──────────────────────────────────────────────────────
export const ORACLE_ABI = [
  "event VerificationRequest(uint256 indexed requestId, uint256 indexed dealId, address indexed dealContract, uint8 reqType, string cadastralNumber, string subjectAddress, string fullName)",
  "event RegistryTransferRequest(uint256 indexed requestId, uint256 indexed dealId, address indexed dealContract, string cadastralNumber, string sellerFullName, string buyerFullName, uint256 priceWei)",
  "event RequestFulfilled(uint256 indexed requestId, bool success)",
];

// ─── RealEstateMarket ABI ────────────────────────────────────────────────────
export const MARKET_ABI = [
  {
    name: "createDeal",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_cadastralNumber",      type: "string"  },
      { name: "_apartmentAddress",     type: "string"  },
      { name: "_propertyDocumentHash", type: "string"  },
      { name: "_registryRecordId",     type: "string"  },
      { name: "_price",                type: "uint256" },
      { name: "_paymentTimeoutSeconds",type: "uint256" },
    ],
    outputs: [{ name: "dealId", type: "uint256" }],
  },
  {
    name: "submitSellerData",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "dealId",             type: "uint256" },
      { name: "_sellerFullName",    type: "string"  },
      { name: "_sellerPassportHash",type: "string"  },
    ],
    outputs: [],
  },
  {
    name: "submitBuyerData",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "dealId",             type: "uint256" },
      { name: "_buyerFullName",     type: "string"  },
      { name: "_buyerPassportHash", type: "string"  },
    ],
    outputs: [],
  },
  {
    name: "reservePayment",
    type: "function",
    stateMutability: "payable",
    inputs: [{ name: "dealId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "cancelDeal",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "dealId", type: "uint256" },
      { name: "reason", type: "string"  },
    ],
    outputs: [],
  },
  {
    name: "cancelDealAsBuyer",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "dealId", type: "uint256" },
      { name: "reason", type: "string"  },
    ],
    outputs: [],
  },
  {
    name: "claimTimeoutCancellation",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "dealId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "getDealMain",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "dealId", type: "uint256" }],
    outputs: [
      { name: "id",              type: "uint256" },
      { name: "seller",          type: "address" },
      { name: "buyer",           type: "address" },
      { name: "stage",           type: "uint8"   },
      { name: "price",           type: "uint256" },
      { name: "contractBalance", type: "uint256" },
      { name: "paymentDeadline", type: "uint256" },
      { name: "createdAt",       type: "uint256" },
      { name: "completedAt",     type: "uint256" },
    ],
  },
  {
    name: "getDealProperty",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "dealId", type: "uint256" }],
    outputs: [
      { name: "cadastralNumber",     type: "string" },
      { name: "apartmentAddress",    type: "string" },
      { name: "registryRecordId",    type: "string" },
      { name: "newRegistryRecordId", type: "string" },
      { name: "lastOracleError",     type: "string" },
    ],
  },
  {
    name: "getDealParties",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "dealId", type: "uint256" }],
    outputs: [
      { name: "sellerFullName", type: "string" },
      { name: "buyerFullName",  type: "string" },
    ],
  },
  {
    name: "getDealTimestamps",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "dealId", type: "uint256" }],
    outputs: [
      { name: "sellerSubmittedAt", type: "uint256" },
      { name: "sellerVerifiedAt",  type: "uint256" },
      { name: "buyerSubmittedAt",  type: "uint256" },
      { name: "buyerVerifiedAt",   type: "uint256" },
      { name: "paymentReceivedAt", type: "uint256" },
      { name: "cancelledAt",       type: "uint256" },
    ],
  },
  {
    name: "getDealCount",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getSellerDeals",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "seller", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    name: "getBuyerDeals",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "buyer", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "event",
    name: "DealCreated",
    inputs: [
      { indexed: true,  name: "dealId",          type: "uint256" },
      { indexed: true,  name: "seller",           type: "address" },
      { indexed: false, name: "price",            type: "uint256" },
      { indexed: false, name: "cadastralNumber",  type: "string"  },
    ],
  },
  {
    type: "event",
    name: "StageChanged",
    inputs: [
      { indexed: true,  name: "dealId",     type: "uint256" },
      { indexed: false, name: "stage",      type: "uint8"   },
      { indexed: false, name: "visualText", type: "string"  },
    ],
  },
  {
    type: "event",
    name: "SellerVerifiedOK",
    inputs: [{ indexed: true, name: "dealId", type: "uint256" }],
  },
  {
    type: "event",
    name: "BuyerVerifiedOK",
    inputs: [{ indexed: true, name: "dealId", type: "uint256" }],
  },
  {
    type: "event",
    name: "PaymentReceived",
    inputs: [
      { indexed: true,  name: "dealId", type: "uint256" },
      { indexed: true,  name: "buyer",  type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "DealCompleted",
    inputs: [
      { indexed: true,  name: "dealId",        type: "uint256" },
      { indexed: true,  name: "buyer",          type: "address" },
      { indexed: false, name: "newRegistryId",  type: "string"  },
    ],
  },
  {
    type: "event",
    name: "DealCancelled",
    inputs: [
      { indexed: true,  name: "dealId", type: "uint256" },
      { indexed: false, name: "reason", type: "string"  },
    ],
  },
];
`;
}
